pipeline {
    agent any

    tools {
        jdk 'JDK17'
        maven 'Maven2'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/cheikhi51/Stage_Appels_Offres_Backend.git'
            }
        }

        stage('Build') {
            steps {
                dir('offerTrack') {
                    bat 'mvn clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('offerTrack') {
                    bat 'mvn test'
                }
            }
        }

        stage('Package') {
            steps {
                dir('offerTrack') {
                    bat 'mvn package -DskipTests'
                }
            }
        }
    }

    post {
        success {
            echo '✅ Backend pipeline completed successfully!'
        }
        failure {
            echo '❌ Backend pipeline failed.'
        }
    }
}
